---

- name: Get upstream APT GPG key
  apt_key:
    id: '{{ nodejs__upstream_key_id }}'
    keyserver: '{{ ansible_local.core.keyserver
                   if (ansible_local|d() and ansible_local.core|d() and
                       ansible_local.core.keyserver)
                   else "hkp://pool.sks-keyservers.net" }}'
    state: 'present'
  when: nodejs__upstream|bool

- name: Configure upstream APT repository
  apt_repository:
    repo: '{{ nodejs__upstream_repository }}'
    state: 'present'
    update_cache: True
  when: nodejs__upstream|bool

- name: Install APT packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ nodejs__base_packages }}'
    - '{{ nodejs__distribution_packages }}'
    - '{{ nodejs__packages }}'
    - '{{ nodejs__group_packages }}'
    - '{{ nodejs__host_packages }}'
    - '{{ nodejs__dependent_packages }}'

- name: Install NPM packages
  npm:
    name:           '{{ item.name           | d(item) }}'
    state:          '{{ item.state          | d("present") }}'
    global:         '{{ (item.global        | d(True)) | bool }}'
    production:     '{{ (item.production    | d(nodejs__npm_production_mode)) | bool }}'
    version:        '{{ item.version        | d(omit) }}'
    registry:       '{{ item.registry       | d(omit) }}'
    executable:     '{{ item.executable     | d(omit) }}'
    ignore_scripts: '{{ item.ignore_scripts | d(omit) }}'
    path:           '{{ item.path           | d(omit) }}'
  with_flattened:
    - '{{ nodejs__npm_packages }}'
    - '{{ nodejs__npm_group_packages }}'
    - '{{ nodejs__npm_host_packages }}'
    - '{{ nodejs__npm_dependent_packages }}'

