---
- name: Remove apache2
  apt: name=apache2 state=absent

- name: Apt via https
  apt: name=apt-transport-https state=present

- name: Install nginx
  action: apt pkg={{ item }} state=installed
  with_items:
   - nginx-extras 

- name: Ensure the nginx configuration file is set
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Set nginx to start on boot
  service: name=nginx enabled=yes

- name: Copy env from hostname script
  copy: src=/scripts/get_env_from_hostname.sh dest=/usr/local/bin/get_env_from_hostname.sh mode=0755

- name: Copy unicorn service script
  copy: src=unicorn dest=/etc/init.d/unicorn mode=0755
